      SUBROUTINE CUPARAM
C
C
C     THIS ROUTINE DEFINES DISPOSABLE PARAMETERS FOR MASSFLUX SCHEME
C
C          M.TIEDTKE         E.C.M.W.F.    2/89
C
C          INTERFACE
C          ---------
C
C          THIS ROUTINE IS CALLED FROM *INIPHY*
C
      INCLUDE 'comcumf.h'
C
C
C-----------------------------------------------------------------------
C
C     1.           SPECIFY PARAMETERS FOR MASSFLUX-SCHEME
C                  --------------------------------------
C
C     ************************************************************
C     ADD LOGICAL VARIABLE *LCUNEW* TO IMPLEMENT MODIFICATIONS
C
      NAMELIST /NAMMF/ LMFNEW,LMFHRES,LMFPRINT,LMFQHFL,LNORDSCV
     +                ,LCLOS_VAPCVG
      DATA LMFNEW/.FALSE./ , LMFHRES /.FALSE./ ,LMFPRINT/.FALSE./ 
      DATA LMFQHFL/.FALSE./, LNORDSCV /.FALSE./
      DATA LCLOS_VAPCVG/.FALSE./
      NUNMF = 19
      NUNNAM=  7
      OPEN (UNIT=NUNMF ,FORM='FORMATTED',STATUS='OLD',FILE='nammf')
      READ  (NUNMF ,NAMMF)
      WRITE (NUNNAM,NAMMF)
      CLOSE (UNIT=NUNMF)
C
      DO JUN=1,2
       IF (JUN.EQ.1) IUNOUT=6
       IF (JUN.EQ.2) IUNOUT=NUNNAM
         IF (LMFNEW) THEN
             WRITE (IUNOUT,'(A)') 
     +       '  *** MODIFICATIONS IN MASS-FLUX SCHEME IMPLEMENTED *** '
         END IF
         IF (LMFHRES) THEN
             WRITE (IUNOUT,'(2A)') 
     +       '  *** HIGH-RESOLUTION MASSIVE DETRAINMENT',
     +              ' IN MASS-FLUX SCHEME USED ***'
         END IF
         IF (LMFQHFL) THEN
             WRITE (IUNOUT,'(2A)') 
     +       '  *** MASS_FLUX AT CLOUD BASE DETERMINED FROM'
     +      ,' KINEMATIC SURFACE VAPOUR FLUX ***'
         ELSE
             WRITE (IUNOUT,'(2A)') 
     +       '  *** MASS_FLUX AT CLOUD BASE DETERMINED FROM'
     +      ,' VAPOUR CONVERGENCE IN PBL ***'
         END IF
         IF (LNORDSCV) THEN
             WRITE (IUNOUT,'(A)') 
     +       '  *** NORDENGS CLOSURE IN SHALLOW CONVECTION USED ***'
         ELSE
             WRITE (IUNOUT,'(A)') 
     +       '  *** ECHAM4 CLOSURE IN SHALLOW CONVECTION USED ***'
         END IF
         IF (LCLOS_VAPCVG) THEN
            WRITE (IUNOUT,'(A)') 
     +      '*** VAPOUR CONVERGENCE CLOSURE IN DEEP CONVECTION USED ***'
         ELSE
             WRITE (IUNOUT,'(A)') 
     +      '*** CAPE CLOSURE IN DEEP CONVECTION USED (IF ECHAM4) ***'
         END IF
      ENDDO
C     ************************************************************
  100 CONTINUE
C
C     ENTRPEN: AVERAGE ENTRAINMENT RATE FOR PENETRATIVE CONVECTION
C     -------
C
      ENTRPEN=1.0E-4
C
C     ENTRSCV: AVERAGE ENTRAINMENT RATE FOR SHALLOW CONVECTION
C     -------
C
      ENTRSCV=3.0E-4
      IF (LMFNEW) ENTRSCV = 2.0E-03
C
C     ENTRMID: AVERAGE ENTRAINMENT RATE FOR MIDLEVEL CONVECTION
C     -------
C
      ENTRMID=1.0E-4
C
C     ENTRDD: AVERAGE ENTRAINMENT RATE FOR DOWNDRAFTS
C     ------
C
      ENTRDD =2.0E-4
C
C     CMFCTOP:   RELATIVE CLOUD MASSFLUX AT LEVEL ABOVE NONBUOYANCY LEVE
C     -------
C
C
C     IN ECHAM MODEL CMFTOP IS DEPENDENT ON *NN*,
C     I.E. MAX MERIDIONAL WAVE NUMBER AT M=0 (DECLARED IN INICTL.dk)
C     ORIGINAL VALUE IS INSERTED!!
C
      CMFCTOP=0.15
C
C     CMFCMAX:   MAXIMUM MASSFLUX VALUE ALLOWED FOR UPDRAFTS ETC
C     -------
C
      CMFCMAX=1.0
C
C     CMFCMIN:   MINIMUM MASSFLUX VALUE (FOR SAFETY)
C     -------
C
      CMFCMIN=1.E-10
C
C     CMFDEPS:   FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
C     -------
C
      CMFDEPS=0.3
C
C     CPRCON:    COEFFICIENTS FOR DETERMINING CONVERSION FROM CLOUD WATE
C     ------
C
      CPRCON =2.0E-4
C
C     NEXT VALUE IS RELATIVE SATURATION IN DOWNDRAFRS
C     BUT IS NO LONGER USED ( FORMULATION IMPLIES SATURATION)
C     -------------------------------------------------------
C
      RHCDD=1.
C
C     THICKNESS OF THE ASSUMED OVERSHOOT LAYER
C     ONLY RELEVANT IN A HIGH RESOLUTION MODE : LMFHRES=.TRUE.
C     --------------------------------------------------------

      DP_SHOOT = 6000.
C
C     CTAUMF:   RELAXATION TIME OF CAPE IN DEEP CONVECTION
C     ------

      CTAUMF = 3600.
C
      RETURN
      END
